### PR TITLE
Update _DataReceiver.py

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Adding missing `__rshift__` and `__lshift__`

### CODE REVIEW

**Comment by slacrherbst** [comment]
Is this necessary? It should pick these up from the Slave base class.

**Comment by ruck314** [comment]
This is why you can't use `<<` or `>>` in wave8 and had to used the `pyrogue.streamConnect()` instead:
https://github.com/slaclab/wave8/blob/master/firmware/python/wave8/Top.py#L233

I have ran into this before when there is multiple parents classes for a single child class:
https://github.com/slaclab/sparkPix-S/blob/master/firmware/python/spark_pix_s/_SimPatternGen.py#L166

**Comment by slacrherbst** [comment]
Interesting. This appears to work in the test script. Have we double checked that this fails:

https://github.com/slaclab/rogue/blob/cad522dece68cc9889d5541f2e53046bf3a6bccd/tests/run_server.py#L110-L113

**Comment by slacrherbst** [comment]
> I have ran into this before when there is multiple parents classes for a single child class:
> https://github.com/slaclab/sparkPix-S/blob/master/firmware/python/spark_pix_s/_SimPatternGen.py#L166

I think that was required because of base class confusion.

**Comment by ruck314** [comment]
`pyrogue.streamConnect(self.epicsUb,d)`  = works
`self.epicsUb >> d` = works
`d << self.epicsUb` = broken
```
Rogue/pyrogue version v5.4.0-27-gfafb7a44. https://github.com/slaclab/rogue
Traceback (most recent call last):
  File "scripts/wave8DAQ.py", line 147, in <module>
    timeout     = 5.0,
  File "/afs/slac.stanford.edu/u/re/ruckman/projects/wave8/firmware/python/wave8/Top.py", line 235, in __init__
    d << self.epicsUb                       # Broken
rogue.GeneralError: memory::Slave::lshiftPy: General Error: Attempt to use << operator with incompatible memory master

**Comment by slacrherbst** [comment]
I just tested the RawDataReceiver.py class in the test script. What error do you get? I wonder if it is related to the other class.

**Comment by ruck314** [comment]
```
Rogue/pyrogue version v5.4.0-27-gfafb7a44. https://github.com/slaclab/rogue
Traceback (most recent call last):
  File "scripts/wave8DAQ.py", line 147, in <module>
    timeout     = 5.0,
  File "/afs/slac.stanford.edu/u/re/ruckman/projects/wave8/firmware/python/wave8/Top.py", line 235, in __init__
    d << self.epicsUb                       # Broken
rogue.GeneralError: memory::Slave::lshiftPy: General Error: Attempt to use << operator with incompatible memory master
```

**Comment by slacrherbst** [comment]
Ok. perhaps the interrogation is bad. I will test that.

**Comment by slacrherbst** [comment]
Ok I see now. It appears the problem is related to the CPP implementation of the lshift code in the slave class (as called in the DataReceiver class). It appears it cannot properly extract the master class from a class that inherits from both a master and a slave (unbatcher/splitter). Let me look into that.

**Comment by slacrherbst** [comment]
I am going to approve and merge this but it is a bandaid fix. The error appears to be in the way boost::python::extract works. It does not properly extract the Master stream class object in the __lshift__ call. This fix can be applied to python subclasses but it does not fix cases where you try to connect a pure C++ slave to a C++ master/slave.

**Pull request merged**
