### PR TITLE
optional configuration dumps

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by bengineerd** [comment]
Use `self.root` instead of `self._root`.

**Comment by slacrherbst** [comment]
would it not be better for performance to use a direct access versus a method? I guess we consider this private and bad practice so better to use self.root?

**Comment by bengineerd** [comment]
Right. _root is private. We should use the public accessors when we have them.

**Comment by jesusvasquez333** [comment]
I will give this try...

**Comment by jesusvasquez333** [comment]
The changes work correctly...

**Pull request merged**
