### PR TITLE
Add thread names

### PR DESCRIPTION
**Pull request by jesusvasquez333**
With these changes, I see this output when running top:

```
Threads:  22 total,   0 running,  22 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.8 us,  4.4 sy,  0.0 ni, 93.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16038172 total, 11330456 free,  1320016 used,  3387700 buff/cache
KiB Swap: 16777212 total, 16777212 free,        0 used. 14370776 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
21671 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:03.63 python3
21692 cryo      20   0 4567564 222848  68692 S  6.6  1.4   0:02.47 AxiStreamDma
21693 cryo      20   0 4567564 222848  68692 S  6.3  1.4   0:01.88 AxiStreamDma
21694 cryo      20   0 4567564 222848  68692 S  6.6  1.4   0:01.89 AxiStreamDma
21695 cryo      20   0 4567564 222848  68692 S  6.6  1.4   0:01.89 AxiStreamDma
21696 cryo      20   0 4567564 222848  68692 S  6.0  1.4   0:01.88 AxiStreamDma
21697 cryo      20   0 4567564 222848  68692 S  6.3  1.4   0:01.88 AxiStreamDma
21698 cryo      20   0 4567564 222848  68692 S  6.3  1.4   0:01.88 AxiStreamDma
21699 cryo      20   0 4567564 222848  68692 S  6.3  1.4   0:01.84 AxiStreamDma
21700 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 ZMQbg/0
21701 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 ZMQbg/1
21702 cryo      20   0 4567564 222848  68692 S  4.3  1.4   0:02.43 python3
21703 cryo      20   0 4567564 222848  68692 S  1.3  1.4   0:00.41 python3
21704 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21705 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21706 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21707 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21708 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21709 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 Fifo
21710 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.03 EpicsV3Server
21711 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.00 QXcbEventQueue
21713 cryo      20   0 4567564 222848  68692 S  0.0  1.4   0:00.01 QDBusConnection
```

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
I'm checking why the python tests failed in travis

**Comment by jesusvasquez333** [comment]
Seems that there is a race condition somewhere in the UDP Client, Server threads, which is worsen by the addition of the thread rename call. I'm seeing the following error:

```
$ python3 test_udpPacketizer.py
Rogue/pyrogue version v3.3.6-1-gdf7b8105. https://github.com/slaclab/rogue
Testing ver=1 jumbo=True
Waiting for RSSI connection
Generating Frames
Closing Link
Done testing ver=1 jumbo=True
Testing ver=2 jumbo=True
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_weak_ptr> >'
  what():  tr1::bad_weak_ptr
Aborted
```

Sometimes the test runs fine.

The test passed when I remove the `pthread_setname_np` from both the UDP Client and Server code.

**Comment by slacrherbst** [comment]
This is the same thread race condition we had before. We need a longer wait in the UDP run thread.

**Comment by slacrherbst** [comment]
I added the thread delays in.

**Comment by slacrherbst** [comment]
I also verified this compiles with std::threads as well.

**Comment by slacrherbst** [comment]
Well it compiles for std::thread but it does not do anything...

**Pull request merged**
