### PR TITLE
Make pickle operation recursive, Use JSON for ZMQ Interface

### PR DESCRIPTION
**Pull request by slacrherbst**
This change makes the node pickle operation recursive, allowing the full tree to be picked in a single operation.

Also addresses a bug where some sub-nodes were not being setup properly and causing errors when right clicking "ReadDevice" on the GUI.

### CODE REVIEW

**Comment by slacrherbst** [comment]
This PR is ready.

**Comment by bengineerd** [comment]
When I toggle the `enable` variable on a Device in the GUI, I see :
```
Traceback (most recent call last):
  File "/u/re/bareese/anaconda3/envs/kpix-env/lib/python3.7/site-packages/pyrogue/_Virtual.py", line 228, in _doUpdate
    n._doUpdate(val)
  File "/u/re/bareese/anaconda3/envs/kpix-env/lib/python3.7/site-packages/pyrogue/_Virtual.py", line 166, in _doUpdate
    func.varListener(self.path,val.value,val.valueDisp)
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by slacrherbst** [comment]
Oh wow. I think this exposed a bug with Enable

**Comment by slacrherbst** [comment]
Yes. See this:
https://github.com/slaclab/rogue/pull/400/commits/e087e4c7ad9a1d1ff88f2e84f9a900e75141319a

**Pull request merged**
