### PR TITLE
Make writeBlocks() obey force when passed a Variable list

### PR DESCRIPTION
**Pull request by bengineerd**
Fixed a bug where `writeBlocks()` would always force if a list of variables was passed to `variable=`.
It now obeys the `force` parameter.

### CODE REVIEW

**Comment by slacrherbst** [comment]
You also need to update the set() method in variable to have force=true in writeBlocks

**Comment by slacrherbst** [comment]
Check post as well

**Comment by bengineerd** [comment]
`RemoteVariable.set()` first calls `Block.set()`, which updates the data mask and causes the Block to be stale even if the value didn't change. So it shouldn't matter if force is true or false. I suppose it's a slight optimization though to just call it with `force=True` so it doesn't have to bother checking `Block.stale`.

RemoteVariable.post() doesn't call writeBlocks, so that should be ok.

**Comment by slacrherbst** [comment]
Yes I guess that is correct.

**Pull request merged**
