### PR TITLE
Remove self referece as Model is now static

### PR DESCRIPTION
**Pull request by jesusvasquez333**

### CODE REVIEW

**Comment by bengineerd** [comment]
@jesusvasquez333 - Can you test out the latest commits in this branch and verify that they work?

**Comment by jesusvasquez333** [comment]
@bengineerd I will try it now...

**Comment by jesusvasquez333** [comment]
We are seeing this error now:

`unsupported operand type(s) for >>: 'int' and 'list'`

**Comment by bengineerd** [comment]
@jesusvasquez333 Can you provide a full stack trace?

**Comment by bengineerd** [comment]
@jesusvasquez333 - I think I fixed the error you are seeing. Give it a try and let me know.

**Comment by jesusvasquez333** [comment]
@bengineerd: Mitch gave it a try and it seems to be working now.

**Pull request merged**
