### PR TITLE
adding flake8 to .travis.yml

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Added python linter to travic CI
- Fixed some bugs in the python code
  - Caught by the linter
- Some mics code header clean up

### CODE REVIEW

**Comment by slacrherbst** [comment]
I am not a fan of this error:
E127 continuation line over-indented for visual indent

**Comment by slacrherbst** [comment]
I am not sure I like this check:
python/pyrogue/_Memory.py:77:80: E501 line too long (170 > 79 characters)
python/pyrogue/_Memory.py:88:80: E501 line too long (95 > 79 characters)
python/pyrogue/_Memory.py:93:80: E501 line too long (85 > 79 characters)

**Comment by ruck314** [comment]
@slacrherbst: E501 already included as an ignore in the tox.ini (flake8 config file)
https://github.com/slaclab/rogue/blob/flake8/tox.ini#L37
Your .flake8 config file conflicts with tox.ini causing tox.ini to not be used

**Comment by slacrherbst** [comment]
Ah that makes sense. I wondered why more errors showed up suddenly.

**Pull request merged**
