### PR TITLE
Add support to commands

### PR DESCRIPTION
**Pull request by jesusvasquez333**
This PR add supports to command from EPICS. Writing to a command's respective PV will execute the *call* of the command. If the command has arguments, the value written to the PV will be use as argument of the *call* method. Also, reading the PVs don't throw an error anymore.

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
@slacrherbst I updated this PR after our discussion.

**Comment by slacrherbst** [comment]
I updated the command decorator to generate LocalCommands. 
value must be passed for LocalCommands which take args

**Comment by slacrherbst** [comment]
@bengineerd Please confirm that the value= is the raw value (returned by get()) and not the display value (returned by value()) . I assumed this when I created the RunControl class.

**Comment by slacrherbst** [comment]
Also please verify setDisp is equivalent to set() for non string types? We may need to change the helper functions in Command to call setDisp so that commands can handle enums, strings, etc from the GUI and config files.

**Comment by slacrherbst** [comment]
Jesus, I changed epics.py a little so that enums are handled for commands as well. I also removed the try: expect: since it is already caught just below the loop.

**Comment by jesusvasquez333** [comment]
@slacrherbst I'm getting this kind of errors after the changes:

`Traceback (most recent call last):
  File "./python/pyrogue_server.py", line 227, in <module>
    main(sys.argv[1:])
  File "./python/pyrogue_server.py", line 219, in main
    server = localServer(ipAddr, serverMode, groupName, epicsPrefix)
  File "./python/pyrogue_server.py", line 96, in __init__
    fpga = FpgaTopLevel(ipAddr=ipAddr)
  File "/tmp/jvasquez/pyrogue/AmcCarrierCryoRtmEthKcu060-0x00000002-20170626105128-ruckman-dirty.python/python/FpgaTopLevel/FpgaTopLevel.py", line 50, in __init__
    enableBsa  =  False
  File "/tmp/jvasquez/pyrogue/AmcCarrierCryoRtmEthKcu060-0x00000002-20170626105128-ruckman-dirty.python/python/AmcCarrierCore/AmcCarrierCore.py", line 76, in __init__
    hidden       =  True,
  File "/tmp/jvasquez/pyrogue/AmcCarrierCryoRtmEthKcu060-0x00000002-20170626105128-ruckman-dirty.python/python/surf/devices/microchip/_Axi24LC64FT.py", line 43, in __init__
    instantiate = instantiate,
  File "/tmp/jvasquez/pyrogue/AmcCarrierCryoRtmEthKcu060-0x00000002-20170626105128-ruckman-dirty.python/python/surf/misc/_GenericMemory.py", line 57, in __init__
    @self.command()
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Device.py", line 358, in _decorator
    self.add(pr.LocalCommand(function=newFunc, **kwargs))
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Command.py", line 128, in __init__
    raise CommandError(f'LocalCommand {self.path} must specify value= argument in constructor when accepting an arg')
pyrogue._Command.CommandError: LocalCommand fill must specify value= argument in constructor when accepting an arg
`

Or this one when I use a data writer

`Traceback (most recent call last):
  File "./python/pyrogue_server.py", line 227, in <module>
    main(sys.argv[1:])
  File "./python/pyrogue_server.py", line 219, in main
    server = localServer(ipAddr, serverMode, groupName, epicsPrefix)
  File "./python/pyrogue_server.py", line 92, in __init__
    stmDataWriter = pyrogue.utilities.fileio.StreamWriter('streamDataWriter')
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/utilities/fileio.py", line 29, in __init__
    pyrogue.DataWriter.__init__(self, name=name, description='Stream Writer',hidden=hidden)
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Device.py", line 391, in __init__
    description='Auto create data file name using data and time.'))
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Command.py", line 128, in __init__
    raise CommandError(f'LocalCommand {self.path} must specify value= argument in constructor when accepting an arg')
pyrogue._Command.CommandError: LocalCommand autoName must specify value= argument in constructor when accepting an arg
`

**Comment by slacrherbst** [comment]
I fixed the issue in the file writer. Looking into surf

**Comment by slacrherbst** [comment]
I think this should work now. @jesusvasquez333 please take a look.

**Comment by jesusvasquez333** [comment]
@slacrherbst It seems to be working now. I only see some device which return **str** as type instead if **string**

`WARNING:pyrogue.EpicsCaServer:Device AMCc:systemLog has type str which is not supported by pcaspy
WARNING:pyrogue.EpicsCaServer:Device AMCc:writeConfig has type str which is not supported by pcaspy
WARNING:pyrogue.EpicsCaServer:Device AMCc:readConfig has type str which is not supported by pcaspy
WARNING:pyrogue.EpicsCaServer:Device AMCc:streamDataWriter:dataFile has type str which is not supported by pcaspy
WARNING:pyrogue.EpicsCaServer:Device AMCc:FpgaTopLevel:AmcCarrierCore:AxiVersion:BuildStamp has type str which is not supported by pcaspy`

I can added the checking in **epics.py**, but is it expected to get **str** as type? 

Also,  it seems that from this checking in **epics.py**

```
d['value'] = node.value()

# All devices should return a not NULL value
if not d['value']:
    self._log.warning("Device {} has a null value".format(d['name']))
```

that all device return a NULL value.

**Comment by slacrherbst** [comment]
I updated a number of items. I left in support for legacy eval() commands because the exist in a number of surf modules (cpsw conversion). We need to fix these and also update the converted cpsw modules to do:

add(RemoteVariable(....))

instead of

addVariable(....)

**Comment by jesusvasquez333** [comment]
@slacrherbst Everything looks good now, aside from the warning message from the legacy commands:

```
WARNING:pyrogue.BaseCommand.Initialize:Using deprecated eval string. Please change to function:                                            for i in range(4):
                                             dev.Init[i].set(1)
                                             dev.Init[i].set(0)
                                          

ERROR:pyrogue.BaseCommand.Initialize:name 'texwrap' is not defined
Traceback (most recent call last):
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Command.py", line 62, in call
    pr.varFuncHelper(self._function,pargs, self._log)
  File "/afs/slac.stanford.edu/u/lt/jvasquez/sandbox/github/rogue/python/pyrogue/_Variable.py", line 585, in varFuncHelper
    exec(texwrap.dedent(func),ns)
NameError: name 'texwrap' is not defined
```

**Comment by slacrherbst** [comment]
I just pushed a fix.

**Comment by slacrherbst** [comment]
@jesusvasquez333 I fixed the last typo big in the legacy support. I am going to merge to master now.

**Pull request merged**
