### PR TITLE
ESROGUE-526: Use portable format specifiers when printing inttypes

### PR DESCRIPTION
**Pull request by mskoufis**
### Description

Replace all `"%i"` and related format specifiers with portable equivalents specified in `<inttypes.h>`.

### JIRA

[ESROGUE 526](https://jira.slac.stanford.edu/browse/ESROGUE-526)

### CODE REVIEW

**Comment by mskoufis** [comment]
This one passes the CI tests but I haven't observed the logging output.  Not sure what is the best way to do this.

**Review by ruck314 — APPROVED** [review]

**Comment by bengineerd** [comment]
Please change these in any exception throws as well.

I did a grep on the code and there are still a lot of `"%i"` and `"%x"` instances still in there.

**Comment by mskoufis** [comment]
Okay.  I only updated the logging.

**Comment by mskoufis** [comment]
@bengineerd Thanks for finding the %i instances in the header file.  I was only looking at the source files not the headers.  Also, I didn't change the sscanf lines in Value.cpp because I wasn't sure if that would change the expected format string and cause any problems.

**Comment by bengineerd** [comment]
@mskoufis 
I think the `sscanf` calls are ok, but they should be SCNu32.
I'm not sure what the right way is to format `struct timeval` members. But what we have is probably ok.

**Pull request merged**
