### PR TITLE
ESROGUE-533: Shutdown Rogue if DmaDriver version mismatch

### PR DESCRIPTION
**Pull request by mskoufis**

### CODE REVIEW

**Comment by ruck314** [comment]
@mskoufis I think you might need to add this to the PgpCard.cpp as well:
https://github.com/slaclab/rogue/blob/master/src/rogue/hardware/pgp/PgpCard.cpp#L69

**Comment by mskoufis** [comment]
@ruck314 Sounds good.  Will do.

**Comment by ruck314** [comment]
@mskoufis I would also update the comment to mention that the new version is a 64-bit address API
```
To use later versions (64-bit address API), you will need to upgrade ....
```

**Comment by ruck314** [comment]
@mskoufis Change this statement `v5.12.2 (or later ... or next release)` to `v5.13.0 (or later)`.  This will assume the next rogue tag release is v.5.13.0

**Review by ruck314 — APPROVED** [review]

**Pull request merged**
