### PR TITLE
ESROGUE-540: PyDM FileWriter - Prevent users from updating the "Data File" string while the file is opened

### PR DESCRIPTION
**Pull request by mskoufis**

### CODE REVIEW

**Review by ruck314 — APPROVED** [review]

**Comment by bengineerd** [comment]
I've tested this and it looks like it works.

While we're at it with this, I think the buttons should be disabled out based on file open status as well.
File not open -> "Close" button disabled
File open -> "Browse", "Auto Name", "Open" disabled

Thoughts @ruck314?

@mskoufis Is this hard to do?

**Comment by mskoufis** [comment]
@bengineerd Im sure it's doable if you think it's nice to have.

**Comment by bengineerd** [comment]
@mskoufis Ok, go ahead and implement it.

**Comment by mskoufis** [comment]
@bengineerd Done.  Seems to work as intended, unless I missed something.

**Comment by bengineerd** [comment]
Can you disable the "Close" button on start-up? It doesn't get disabled until a file has been opened and then closed.

**Comment by mskoufis** [comment]
I believe this is ready for integration.

**Pull request merged**
