### PR TITLE
Add ability to pass variable list to block methods

### PR DESCRIPTION
**Pull request by slacrherbst**
With this PR in a device you can queue up a list of specific variables for operations using the device block methods. For example to read a list of variables to update a linked variable.

`````
self.readBlocks(variable=linkVar.dependencies)
self.checkBlocks(variable=linkVar.dependencies)
`````

### CODE REVIEW

**Comment by bengineerd** [comment]
Should we check that all the Variables passed to `readBlocks` actually belong to the Device?

Also, maybe it's useful to pass the list of Variables to `readBlocks` as strings?

```python
self.readBlocks(variable=[f'Reg{x}' for x in range(10)])
```

**Comment by slacrherbst** [comment]
I am not sure it matters if the variables are in the current device since the blocks are reference directly. As for the string option, most likely this is coming from a dependencies list anyway.

**Comment by slacrherbst** [comment]
Can we just do the following as a check:

`````
for v in variables:
     if v._parent is not self:
`````

**Comment by bengineerd** [comment]
Yes, that is probably better.

**Pull request merged**
