### PR TITLE
ESROGUE-532: Bug fix for bad weak_ptr when calling shared_from_this()

### PR DESCRIPTION
**Pull request by mskoufis**
### Description
The call to shared_from_this() from within a thread would fail due to the constructor launching that thread not completing in time.

### JIRA:
[ESROGUE-532](https://jira.slac.stanford.edu/browse/ESROGUE-532)

### Issues
#823

### CODE REVIEW

**Comment by mskoufis** [comment]
@slacrherbst Can you review this when you get a chance?  I'd like to close out this week, if at all possible.

**Comment by slacrherbst** [comment]
The idea is that the weak pointer expires when the constructor exist?

**Comment by mskoufis** [comment]
Yes indeed

**Comment by slacrherbst** [comment]
Clever. We should also apply this fix to other classes that start a thread with a shared from this call in run thread.

**Comment by mskoufis** [comment]
You mean as part of this fix or as a separate ticket?

**Comment by slacrherbst** [comment]
Good question either works. Here is an example of another place we added a sleep:

https://github.com/slaclab/rogue/blob/4be0e9a4d17bdd3987a268f54ad195ee1093190d/src/rogue/hardware/axi/AxiStreamDma.cpp#L371

**Comment by mskoufis** [comment]
Okay I see.  I'll search for usleep then and see what else comes up.

**Review by bengineerd — APPROVED** [review]

**Pull request merged**
