### PR TITLE
ESROGUE 514 - Integrate XVC Server into Rogue

### PR DESCRIPTION
**Pull request by mskoufis**
Integrate XVC Server into Rogue

### Description

Added the Xvc class to interface with the xvc server (as originally used in surf/protocols/jtag/xvcSrv/src/).  The Xvc class inherits from both stream master and slave and hence interfaces with other rogue objects by exchanging rogue streams.

### Details

In your firmware project, modify _Root.py as following:

For RUDP running on FPGA:
```
# Create XVC and UDP client
self.udpClient = rogue.protocols.udp.Client( ip, 2542, False ) # Client(host, port, jumbo)
self.xvc = rogue.protocols.xilinx.Xvc ( 2542 ) # Server(port)
self.addProtocol( self.xvc )

# Connect the UDP Client to XVC
self.udpClient == self.xvc

```

For AXIS data:
```
# Create (Xilinx Virtual Cable) XVC on localhost
self.xvc = rogue.protocols.xilinx.Xvc( 2542 )                                                
self.addProtocol( self.xvc )

# Connect dmaStream[ VC = 2 ] to XVC
self.dmaStream[ 2 ] == self.xvc

```
### JIRA

ESROGUE-514

### CODE REVIEW

**Comment by ruck314** [comment]
@mskoufis Can we change the code so we don't get this warning message when we build rogue?
```make
/u/re/ruckman/projects/rogue/src/rogue/protocols/xilinx/XvcDrvUdp.cpp: In constructor ‘rogue::protocols::xilinx::JtagDriverUdp::JtagDriverUdp(int, char* const*, const char*)’:
/u/re/ruckman/projects/rogue/src/rogue/protocols/xilinx/XvcDrvUdp.cpp:118:48: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
  118 |   snprintf(buf, sizeof(buf), "getaddrinfo for '%s' failed: %s", target, gai_strerror(stat));
      |                                                ^~
In file included from /usr/include/stdio.h:867,
                 from /usr/include/c++/9/cstdio:42,
                 from /usr/include/c++/9/ext/string_conversions.h:43,
                 from /usr/include/c++/9/bits/basic_string.h:6496,
                 from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/stdexcept:39,
                 from /u/re/ruckman/projects/rogue/include/rogue/protocols/xilinx/XvcDriver.h:22,
                 from /u/re/ruckman/projects/rogue/include/rogue/protocols/xilinx/XvcDrvUdp.h:20,
                 from /u/re/ruckman/projects/rogue/src/rogue/protocols/xilinx/XvcDrvUdp.cpp:17:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 28 or more bytes (assuming 283) into a destination of size 256
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mskoufis** [comment]
@ruck314 I don't see that when I build my branch.  What host are you running on again, so I can look into that?

**Comment by ruck314** [comment]
@mskoufis rdsrv303

**Comment by mskoufis** [comment]
The only issue I see right now with this is that the main thread is blocked waiting for the xvc server thread to join().  Surprisingly this doesn't happen on my rhel machine, but I did observe it on rdsrv303 (ubuntu).  Will keep testing and figure this out.

**Comment by bengineerd** [comment]
@slacrherbst @mskoufis Let me know when this is ready to merge.

**Comment by mskoufis** [comment]
@bengineerd @ruck314 @slacrherbst The changes we agreed upon are checked in.  Please review when you have time so we either revise and/or close this out.

**Review by bengineerd — APPROVED** [review]

**Pull request merged**
