### PR TITLE
Add WO support in yaml variable load

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by ruck314** [comment]
I have just try this branch and I am still not able to use YAML to update 'WO' registers.
Here's my YAML:
```
Top:
  RxPhy[0]:
    ActiveLanes: 0xF
```
https://github.com/slaclab/atlas-rd53-daq/blob/pre-release/software/python/common/RxPhy.py#L515

**Comment by slacrherbst** [comment]
With full debugging on do you see the write attempt?

**Comment by ruck314** [comment]
```

**Comment by ruck314** [comment]
```
rogue.Logging.setLevel(rogue.Logging.Warning)
rogue.Logging.setFilter("pyrogue.SrpV3",rogue.Logging.Debug)
rogue.Logging.setLevel(rogue.Logging.Debug)
```
I turned on these filters.  But nothing was printed out after doing the YAML load

**Comment by bengineerd** [comment]
I think this is the problem:
```python
@pr.command(order=1, name='eRadConfig', value='', description='Read configuration from passed filename in YAML format')
    def _readConfig(self,arg):
        """Read YAML configuration from a file. Called from command"""
        try:
            with open(arg,'r') as f:
                self.setYaml(f.read(),False,['RW'])
        except Exception as e:
            self._log.exception(e)
```

**Comment by slacrherbst** [comment]
Yes I did not go high enough in the levels.

**Comment by slacrherbst** [comment]
Ok. I updated the command. Try again.

**Comment by ruck314** [comment]
screencapture
Writing to 'WO' variables now work via YAML.  Thanks for the update.

**Pull request merged**
