### PR TITLE
ESROGUE-545: Disable Load and Save buttons in GUI when file text fields are blank

### PR DESCRIPTION
**Pull request by mskoufis**
### Description
Disable `Load Config`, `Save Config` and `Save State` buttons when the file path boxes are empty.

### JIRA
https://jira.slac.stanford.edu/browse/ESROGUE-545

### CODE REVIEW

**Comment by ruck314** [comment]
@mskoufis I am unable to open/define the file that I want to create:
image

**Comment by mskoufis** [comment]
@ruck314 Is that when you do Load Config?  It sounds like it's expecting an existing configuration file?

**Comment by mskoufis** [comment]
@ruck314 I incorporated your suggestions and it's ready to test again.

**Comment by ruck314** [comment]
@mskoufis One issue that might come up is that you have to use the browser to enable the button.  So a user would not be able to cut/paste the path into the test box.  Can you update the buttons to enable if text is typed into the text box?
image

**Comment by mskoufis** [comment]
@ruck314 I already did that for load config.  Can you test?  I will implement it for the other two cases (i.e. save config, save state).

**Comment by ruck314** [comment]
@mskoufis Behavior for load config.  Go ahead an apply to other two buttons

**Comment by mskoufis** [comment]
@ruck314 It should be done and ready to go.

**Review by ruck314 — APPROVED** [review]
Looks good now.  Ready to merge

**Pull request merged**
