### PR TITLE
Reset name change, better overlap checks

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by slacrherbst** [comment]
Looks good.

**Comment by slacrherbst** [comment]
Should we merge this?

**Comment by bengineerd** [comment]
I haven't actually tested it. Let me merge it into my hps-dev branch and make sure it works first.

**Comment by slacrherbst** [comment]
Can we take another look at this?

**Comment by bengineerd** [comment]
I'll take a look right now.

**Comment by bengineerd** [comment]
I merged it into one of my projects and it seems to work.

**Pull request merged**
