### PR TITLE
Updated edit fields

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by slacrherbst** [comment]
Yes your are correct. I will correct the init line to take advantage of that. The way it was previously written was not working.

**Comment by bengineerd** [comment]
Or more specifically, when extending Device, it's probably better for all the args that will be passed straight to the Device __init__ to be rolled into **kwargs.

**Comment by bengineerd** [comment]
DataWriter could have `hidden` rolled into `**kwargs` as well.

**Comment by slacrherbst** [comment]
I want a different default value for hidden for DataWriter and RunControl

**Comment by bengineerd** [comment]
Ahh, ok.

**Pull request merged**
