### PR TITLE
Deprecate beginWrite and beginRead FrameIterator creators

### PR DESCRIPTION
**Pull request by slacrherbst**
This PR simplifies the FrameIterator use modes by adding Frame::begin() and Frame::end() iterator access methods, deprecating Frame::beginRead() and Frame::beginWrite. In the new use model the user will first specify the payload size of a frame using Frame::setPayload() and then create a single type of iterator, instead of read and write iterators as previously described.

### CODE REVIEW

**Comment by bengineerd** [comment]
The naming of `setPayload()` still bugs me. Can we add a `setPayloadSize()` method, and deprecate `setPayload()` so that it still works for a while? Maybe it would be better in a separate PR but I think we should do it.

**Comment by jesusvasquez333** [comment]
I would suggest instead, using a method name following what STL containers do, and rename `setPayload` to `reserve`: http://www.cplusplus.com/reference/vector/vector/reserve/

**Review by jesusvasquez333 — APPROVED** [review]
I didn't have a chance to test the new code, but I agree with the general idea of using only `begin` and `end` methods

**Comment by slacrherbst** [comment]
The only problem with using reserve, is it make no distinction between the ray capacity of the frame/buffer combination versus what is considered valid data. reserve would be more consistent with the raw data size, versus the actual size of the contents.

**Comment by jesusvasquez333** [comment]
Yes, correct. But isn't that the case for `setPayload` as well? 

I think all these functinalities are supported already on STL, by a combination of `reserve`, `size` and `capacity` methods.

**Comment by slacrherbst** [comment]
I guess the difference is that setPayload is a way to indicate what portion of the "reserved" data is valid. Where the reserved space can be equal to or greater than the actual data being contained. We would need to find the equivalent call for a std::container, which I am not really seeing.

**Comment by jesusvasquez333** [comment]
Yes, you are right. `reserve` just modify the allocate space, but the size reported by `size` in not affected. The container size changes when new elements are inserted/removed. 

So, `setPayload` would be a sort of `setSize` which doesn't exist (AFAIK) in them.

**Comment by bengineerd** [comment]
But isn't the buffer vs "reserved" size distinction an implementation detail that should be hidden from the user at the API level?

More generally, to what extent does an end user really need to know about the details of Rogue's underlying buffer implementation? Personally, I think it's preferable for the API to basically pretend that 1 Frame = 1 buffer. You could still provide some low level methods to query the gritty details for debugging and profiling.

**Comment by slacrherbst** [comment]
In most cases the user will use the higher level API calls in the Frame and not care about buffers. There are some cases where because of performance you will want to handle the frames at the buffer level to make use of known contiguous memory.

**Pull request merged**
